/**
 * The README's "### Code generator" example, compiled and executed.
 *
 * This file is the example — CORELIB_PLAN §9.5 requires that section to show
 * both halves of the generated surface (the one-shot `encode()` / `decode()`
 * helpers *and* the streaming `serialize` / `decoder()` path, §6.1.1), and a
 * snippet nobody runs is a snippet that rots. `readme-generator-example.test.ts`
 * asserts that the fenced block in the README is character-for-character this
 * module (minus the trailing exports, and with the package specifier in place of
 * the relative import), then checks that what it does is what the README claims
 * it does.
 *
 * Everything below the import is the README block verbatim. Keep the two in
 * step: change one, change the other.
 */

import {
  OStream,
  growingOStream,
  Cursor,
  IStream,
  DecodeStatus,
  type FlushSink,
  type Visitor,
} from "../../src/index.js";

// generated by: sofabgen --lang typescript
class Point {
  x = 0;
  y = 0;

  serialize(os: OStream): void {
    os.writeSigned(1, this.x);
    os.writeSigned(2, this.y);
  }

  static decode(bytes: Uint8Array): Point {
    return Point.decodeFrom(new Cursor(bytes));
  }

  static decodeFrom(c: Cursor): Point {
    const p = new Point();
    while (c.readHeader()) {
      switch (c.id) {
        case 1: p.x = Number(c.readSigned()); break;
        case 2: p.y = Number(c.readSigned()); break;
        // case 3: p.child = Child.decodeFrom(c); break;  // nested sequence
        default: c.skip(c.wire); break;                   // forward-compatible
      }
    }
    return p;
  }

  /** The streaming half: a reader bound to the corelib's resumable IStream. */
  static decoder(): PointDecoder {
    return new PointDecoder();
  }
}

// generated alongside it: the visitor that fills a Point, one callback per
// wire type instead of one `case` per id
class PointVisitor implements Visitor {
  private readonly out: Point;
  constructor(out: Point) { this.out = out; }

  signed(id: number, v: number | bigint): void {
    if (id === 1) this.out.x = Number(v);
    else if (id === 2) this.out.y = Number(v);
    // no branch for an unknown id — or for a field whose wire type is not
    // `signed` — so it is skipped and the decode stays COMPLETE (§7.3)
  }
}

// ...and the handle Point.decoder() returns: an IStream plus its destination
class PointDecoder {
  readonly message = new Point();
  private readonly is = new IStream();
  private readonly vis = new PointVisitor(this.message);

  feed(chunk: Uint8Array): DecodeStatus { return this.is.feed(chunk, this.vis); }
  status(): DecodeStatus { return this.is.status(); }
}

const p = new Point(); p.x = 3; p.y = 4;

// one-shot: encode into memory, decode a whole buffer
const os = growingOStream(); p.serialize(os);
const wire = os.bytes().slice();
const got = Point.decode(wire);            // got.x === 3, got.y === 4

// streaming out: the same serialize(), over a 4-byte buffer with a sink
const parts: Uint8Array[] = [];
const sink: FlushSink = (chunk) => { parts.push(chunk.slice()); };
const so = new OStream(new Uint8Array(4), 0, sink);
p.serialize(so); so.flush();               // the same bytes, in pieces

// streaming in: feed those pieces — or any other chunking — to the decoder
const dec = Point.decoder();
let st: DecodeStatus = DecodeStatus.Complete;   // zero bytes end on a boundary
for (const part of parts) st = dec.feed(part);

// COMPLETE says the bytes so far ended on a field boundary, not that the
// message is over — the caller's framing decides that, and a still-INCOMPLETE
// status once the input really has ended is truncation (§5.2).
const streamed = st === DecodeStatus.Complete ? dec.message : null;

export { Point, PointDecoder, PointVisitor, wire, got, parts, st, streamed };
