/**
 * Loader + replayer for the shared `test_vectors.json` conformance suite.
 *
 * The vectors are the cross-language ground truth (generated by the C reference,
 * consumed identically by every implementation). {@link loadVectors} parses them
 * with full 64-bit fidelity and {@link encodeFields} replays a vector's field
 * list onto an {@link OStream}, mapping each `op` to the matching writer.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { OStream } from "../../src/index.js";
import { hexToBytes } from "./hex.js";
import { parseJsonWithBigInt } from "./json-bigint.js";

export interface Field {
  op: string;
  id?: number;
  value?: bigint | number | string | boolean;
  value_hex?: string;
  element_type?: string;
  values?: (bigint | number | string)[];
}

export interface Vector {
  name: string;
  group: string;
  description: string;
  /** Start offset passed to the encoder (defaults to 0). */
  offset?: number;
  /** Optional capability tags; a full-featured build ignores them and runs all. */
  requires?: string[];
  /** Optional field ids a receiver is expected to auto-skip while decoding. */
  skip_ids?: number[];
  fields: Field[];
  serialized: { length: number; hex: string };
}

/**
 * Load the shared vectors.
 *
 * **Which column this repo asserts: `serialized`, and only `serialized`.** It is
 * the primitive-layer ground truth — the exact bytes a `fields` replay through
 * the raw writer surface must produce, and the exact bytes the decoder must
 * accept — so it is the one form a corelib can both emit and verify. Every
 * vector test here (`vectors.test.ts`, `istream.chunked.test.ts`,
 * `skip-ids.test.ts`) compares against it.
 *
 * The file also carries a **`serialized_sparse`** column — the MESSAGE_SPEC §2
 * canonical form, with every all-default sequence *field* omitted rather than
 * framed empty. Nothing in this repo reads it, deliberately and permanently: it
 * is a **message-layer** form, and choosing which sequences are all-default
 * (and therefore which closer applies, §5.1) is a decision only generated code
 * holds. A corelib has no message layer and cannot produce it. That column is
 * consumed by the *generator's* conformance drivers — `sofabgen`'s
 * `tests/conformance/<lang>/run.sh`, which generates message classes from the
 * schema and byte-compares their `encode()` output against it. The absence of a
 * `serialized_sparse` test here is therefore not a coverage gap; a test for it
 * could only be written by re-implementing the message layer in the test.
 * `Vector` above intentionally does not declare the field.
 */
export function loadVectors(): Vector[] {
  const path = fileURLToPath(new URL("../../assets/test_vectors.json", import.meta.url));
  const doc = parseJsonWithBigInt(readFileSync(path, "utf8")) as unknown as {
    vectors: Vector[];
  };
  return doc.vectors;
}

/**
 * A negative UTF-8 vector (top-level `invalid_utf8` array). `string_hex` is the
 * raw string payload that a strict encoder must refuse; `serialized_hex` is the
 * full wire message a strict decoder must reject as the `INVALID` outcome. The
 * `invalid_utf8` key is tracked by corelib-c-cpp#97 (source of truth).
 */
export interface InvalidUtf8Vector {
  name: string;
  group: string;
  description: string;
  requires?: string[];
  id: number;
  string_hex: string;
  serialized_hex: string;
  decode_outcome: "invalid";
  encode_outcome: "invalid_argument";
}

export function loadInvalidUtf8(): InvalidUtf8Vector[] {
  const path = fileURLToPath(new URL("../../assets/test_vectors.json", import.meta.url));
  const doc = parseJsonWithBigInt(readFileSync(path, "utf8")) as unknown as {
    invalid_utf8?: InvalidUtf8Vector[];
  };
  return doc.invalid_utf8 ?? [];
}

/**
 * A growth case (top-level `sequence_growth`) — CORELIB_PLAN §7.2 item 8.
 *
 * Keyed by a **delivery sequence of element ids**, not by bytes: a wrapper array
 * carries no count, so its length is *highest present id + 1* (MESSAGE_SPEC §5.1)
 * and two ports that grow differently emit identical bytes. The port builds the
 * message from `deliver` and asserts `expect`.
 *
 * Indices are **cap-relative**: `id_from_cap` / `length_from_cap` are offsets added
 * to the port's own configured `max_dyn_array_count`, which §6.2.1 deliberately
 * leaves per-target. Every case assumes a cap of at least 4.
 */
export interface GrowthCase {
  name: string;
  group: string;
  description: string;
  requires?: string[];
  /** The wrapper array field's id in the top-level scope. */
  field_id: number;
  /** `string` — a leaf element; `struct` — a framed element with one `unsigned` at id 0. */
  element_type: "string" | "struct";
  deliver: { id?: number; id_from_cap?: number; value: string | bigint | number }[];
  expect: {
    outcome: "complete" | "limit_exceeded";
    length?: number;
    length_from_cap?: number;
    default_ids?: number[];
    terminal?: boolean;
    max_length?: number;
  };
}

/**
 * Load the growth cases, or `[]` on a vector file that predates them.
 *
 * This port declares `dynamic_arrays`: its wrapper-array containers are JS arrays
 * that grow at decode time, so the block applies (a statically bounded profile
 * skips it and says so instead).
 */
export function loadGrowthCases(): GrowthCase[] {
  const path = fileURLToPath(new URL("../../assets/test_vectors.json", import.meta.url));
  const doc = parseJsonWithBigInt(readFileSync(path, "utf8")) as unknown as {
    sequence_growth?: GrowthCase[];
  };
  // The bigint-fidelity parser is right for a vector's *values* and wrong for its
  // ids, lengths and offsets: those index things, and index arithmetic on a
  // `bigint` throws the moment it meets a `number`. Narrow them here, once, and
  // leave only `deliver[].value` — a real u64 domain — as the parser produced it.
  return (doc.sequence_growth ?? []).map((c) => ({
    ...c,
    field_id: Number(c.field_id),
    deliver: c.deliver.map((el) => ({
      ...(el.id !== undefined ? { id: Number(el.id) } : {}),
      ...(el.id_from_cap !== undefined ? { id_from_cap: Number(el.id_from_cap) } : {}),
      value: el.value,
    })),
    expect: {
      ...c.expect,
      ...(c.expect.length !== undefined ? { length: Number(c.expect.length) } : {}),
      ...(c.expect.length_from_cap !== undefined
        ? { length_from_cap: Number(c.expect.length_from_cap) }
        : {}),
      ...(c.expect.max_length !== undefined ? { max_length: Number(c.expect.max_length) } : {}),
      ...(c.expect.default_ids !== undefined
        ? { default_ids: c.expect.default_ids.map(Number) }
        : {}),
    },
  }));
}

/**
 * Replay a vector's fields onto `os`, exercising the public writer surface.
 *
 * A vector's `serialized` form is the primitive-layer ground truth and always
 * carries the frame, so every `sequence_end` op closes with
 * {@link OStream.writeSequenceEndKeep}: identical bytes once the sequence has
 * content, and the empty-sequence vectors keep their `begin`+`end` pair instead
 * of vanishing (MESSAGE_SPEC §2). The sparse-canonical form the new closer
 * produces is the vectors' separate `serialized_sparse` field.
 */
export function encodeFields(os: OStream, fields: Field[]): void {
  for (const f of fields) {
    const id = Number(f.id ?? 0);
    switch (f.op) {
      case "unsigned":
        os.writeUnsigned(id, f.value as bigint);
        break;
      case "signed":
        os.writeSigned(id, f.value as bigint);
        break;
      case "boolean":
        os.writeBoolean(id, f.value as boolean);
        break;
      case "fp32":
        os.writeFp32(id, Number(f.value));
        break;
      case "fp64":
        os.writeFp64(id, Number(f.value));
        break;
      case "string":
        os.writeString(id, f.value as string);
        break;
      case "blob":
        os.writeBlob(id, hexToBytes(f.value_hex!));
        break;
      case "array":
        encodeArray(os, id, f.element_type!, f.values!);
        break;
      case "sequence_begin":
        os.writeSequenceBeginLazy(id);
        break;
      case "sequence_end":
        os.writeSequenceEndKeep();
        break;
      default:
        throw new Error(`unknown vector op: ${f.op}`);
    }
  }
}

/** Float vectors encode the IEEE specials +inf / -inf / nan as JSON strings. */
function toFloat(x: bigint | number | string): number {
  if (typeof x === "string") {
    if (x === "inf") return Infinity;
    if (x === "-inf") return -Infinity;
    if (x === "nan") return NaN;
    return Number(x);
  }
  return Number(x);
}

function encodeArray(os: OStream, id: number, elementType: string, values: (bigint | number | string)[]): void {
  switch (elementType) {
    case "u8":
    case "u16":
    case "u32":
    case "u64":
      os.writeUnsignedArray(id, values as (bigint | number)[]);
      break;
    case "i8":
    case "i16":
    case "i32":
    case "i64":
      os.writeSignedArray(id, values as (bigint | number)[]);
      break;
    case "fp32":
      os.writeFp32Array(id, values.map(toFloat));
      break;
    case "fp64":
      os.writeFp64Array(id, values.map(toFloat));
      break;
    default:
      throw new Error(`unknown array element type: ${elementType}`);
  }
}
