/**
 * Loader + replayer for the shared `test_vectors.json` conformance suite.
 *
 * The vectors are the cross-language ground truth (generated by the C reference,
 * consumed identically by every implementation). {@link loadVectors} parses them
 * with full 64-bit fidelity and {@link encodeFields} replays a vector's field
 * list onto an {@link OStream}, mapping each `op` to the matching writer.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { OStream } from "../../src/index.js";
import { hexToBytes } from "./hex.js";
import { parseJsonWithBigInt } from "./json-bigint.js";

export interface Field {
  op: string;
  id?: number;
  value?: bigint | number | string | boolean;
  value_hex?: string;
  element_type?: string;
  values?: (bigint | number | string)[];
}

export interface Vector {
  name: string;
  group: string;
  description: string;
  /** Start offset passed to the encoder (defaults to 0). */
  offset?: number;
  /** Optional capability tags; a full-featured build ignores them and runs all. */
  requires?: string[];
  /** Optional field ids a receiver is expected to auto-skip while decoding. */
  skip_ids?: number[];
  fields: Field[];
  serialized: { length: number; hex: string };
}

export function loadVectors(): Vector[] {
  const path = fileURLToPath(new URL("../../assets/test_vectors.json", import.meta.url));
  const doc = parseJsonWithBigInt(readFileSync(path, "utf8")) as unknown as {
    vectors: Vector[];
  };
  return doc.vectors;
}

/**
 * A negative UTF-8 vector (top-level `invalid_utf8` array). `string_hex` is the
 * raw string payload that a strict encoder must refuse; `serialized_hex` is the
 * full wire message a strict decoder must reject as the `INVALID` outcome. The
 * `invalid_utf8` key is tracked by corelib-c-cpp#97 (source of truth).
 */
export interface InvalidUtf8Vector {
  name: string;
  group: string;
  description: string;
  requires?: string[];
  id: number;
  string_hex: string;
  serialized_hex: string;
  decode_outcome: "invalid";
  encode_outcome: "invalid_argument";
}

export function loadInvalidUtf8(): InvalidUtf8Vector[] {
  const path = fileURLToPath(new URL("../../assets/test_vectors.json", import.meta.url));
  const doc = parseJsonWithBigInt(readFileSync(path, "utf8")) as unknown as {
    invalid_utf8?: InvalidUtf8Vector[];
  };
  return doc.invalid_utf8 ?? [];
}

/** Replay a vector's fields onto `os`, exercising the public writer surface. */
export function encodeFields(os: OStream, fields: Field[]): void {
  for (const f of fields) {
    const id = Number(f.id ?? 0);
    switch (f.op) {
      case "unsigned":
        os.writeUnsigned(id, f.value as bigint);
        break;
      case "signed":
        os.writeSigned(id, f.value as bigint);
        break;
      case "boolean":
        os.writeBoolean(id, f.value as boolean);
        break;
      case "fp32":
        os.writeFp32(id, Number(f.value));
        break;
      case "fp64":
        os.writeFp64(id, Number(f.value));
        break;
      case "string":
        os.writeString(id, f.value as string);
        break;
      case "blob":
        os.writeBlob(id, hexToBytes(f.value_hex!));
        break;
      case "array":
        encodeArray(os, id, f.element_type!, f.values!);
        break;
      case "sequence_begin":
        os.writeSequenceBegin(id);
        break;
      case "sequence_end":
        os.writeSequenceEnd();
        break;
      default:
        throw new Error(`unknown vector op: ${f.op}`);
    }
  }
}

/** Float vectors encode the IEEE specials +inf / -inf / nan as JSON strings. */
function toFloat(x: bigint | number | string): number {
  if (typeof x === "string") {
    if (x === "inf") return Infinity;
    if (x === "-inf") return -Infinity;
    if (x === "nan") return NaN;
    return Number(x);
  }
  return Number(x);
}

function encodeArray(os: OStream, id: number, elementType: string, values: (bigint | number | string)[]): void {
  switch (elementType) {
    case "u8":
    case "u16":
    case "u32":
    case "u64":
      os.writeUnsignedArray(id, values as (bigint | number)[]);
      break;
    case "i8":
    case "i16":
    case "i32":
    case "i64":
      os.writeSignedArray(id, values as (bigint | number)[]);
      break;
    case "fp32":
      os.writeFp32Array(id, values.map(toFloat));
      break;
    case "fp64":
      os.writeFp64Array(id, values.map(toFloat));
      break;
    default:
      throw new Error(`unknown array element type: ${elementType}`);
  }
}
